In [1]:
import csv
import tqdm

rows = []
with open('train.csv', 'r') as file:
    reader = csv.DictReader(file)
    for row in tqdm.tqdm(reader):
        rows.append(row)

125497040it [07:42, 271264.20it/s]

In [9]:
import polars as pl

df = pl.DataFrame(rows[:])
df

shape: (125_497_040, 6)
┌───────────┬────────────┬───────────┬──────────┬────────────┬─────────────┐
│ id        ┆ date       ┆ store_nbr ┆ item_nbr ┆ unit_sales ┆ onpromotion │
│ ---       ┆ ---        ┆ ---       ┆ ---      ┆ ---        ┆ ---         │
│ str       ┆ str        ┆ str       ┆ str      ┆ str        ┆ str         │
╞═══════════╪════════════╪═══════════╪══════════╪════════════╪═════════════╡
│ 0         ┆ 2013-01-01 ┆ 25        ┆ 103665   ┆ 7.0        ┆             │
│ 1         ┆ 2013-01-01 ┆ 25        ┆ 105574   ┆ 1.0        ┆             │
│ 2         ┆ 2013-01-01 ┆ 25        ┆ 105575   ┆ 2.0        ┆             │
│ 3         ┆ 2013-01-01 ┆ 25        ┆ 108079   ┆ 1.0        ┆             │
│ 4         ┆ 2013-01-01 ┆ 25        ┆ 108701   ┆ 1.0        ┆             │
│ …         ┆ …          ┆ …         ┆ …        ┆ …          ┆ …           │
│ 125497035 ┆ 2017-08-15 ┆ 54        ┆ 2089339  ┆ 4.0        ┆ False       │
│ 125497036 ┆ 2017-08-15 ┆ 54        ┆ 2106464  ┆ 1.0        ┆ True        │
│ 125497037 ┆ 2017-08-15 ┆ 54        ┆ 2110456  ┆ 192.0      ┆ False       │
│ 125497038 ┆ 2017-08-15 ┆ 54        ┆ 2113914  ┆ 198.0      ┆ True        │
│ 125497039 ┆ 2017-08-15 ┆ 54        ┆ 2116416  ┆ 2.0        ┆ False       │
└───────────┴────────────┴───────────┴──────────┴────────────┴─────────────┘

In [4]:
import psycopg2

ModuleNotFoundError: No module named 'psycopg2'

In [20]:
df[(df['item_nbr'] == '567623') && (df['store_nbr'] == '1')]

ValueError: expected 6 values when selecting columns by boolean mask, got 125497040

In [ ]:
# count by unique values of column onpromotion
df.group_by("onpromotion").agg([pl.len()])

shape: (3, 2)
┌─────────────┬──────────┐
│ onpromotion ┆ len      │
│ ---         ┆ ---      │
│ str         ┆ u32      │
╞═════════════╪══════════╡
│             ┆ 21657651 │
│ False       ┆ 96028767 │
│ True        ┆ 7810622  │
└─────────────┴──────────┘

In [17]:
# cast the column onpromotion from string to boolean
# avoid error: AttributeError: 'DataFrame' object has no attribute 'with_column'

AttributeError: 'DataFrame' object has no attribute 'with_column'

In [11]:

df['onpromotion'] = df['onpromotion'].cast(pl.bool)

AttributeError: module 'polars' has no attribute 'bool'